/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dailyprogramming;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Christopher
 */
public class DailyProgrammingPasswordProtection extends javax.swing.JFrame {

    private static final long SALT = ("audivistine aliquando Tragoediam Darth Plagueis Sapientis?"
            + " sic scii. Jeditum non est hanc fabulam narrare. scriptum est apud Sithia. Darth "
            + "Plagueis Dominus Ater Sithium erat, tam potens sapiensque ut Vi uti posset ad midichlorianes "
            + "gubernandos, itaque vitam creare. tantam scientiam Partis Atrae habebat ut etiam e leto amatos "
            + "sibi servare posset. Pars Atra Vis via est ad multas facultates ab aliquibus monstruosas esse "
            + "putatas... tam potens est factus ut timeret ille tantummodo potentiam amittere, quod scilicet "
            + "tandem fecit. infeliciter cum omnia sibi scita discipulum docuisset, iste discipulus dormientem "
            + "necavit. ironia est. alios nec se servare poterat.").hashCode();

    private static HashMap<Long, Long> Data = new HashMap<>();

    /**
     * Creates new form DailyProgrammingPasswordProtection
     */
    public DailyProgrammingPasswordProtection() {
        readAllHashes();
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (saveHashes());
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogIn = new javax.swing.JButton();
        btnChangeAccount = new javax.swing.JButton();
        txfUsername = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        btnChangeAccount.setText("Create Account");
        btnChangeAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeAccountActionPerformed(evt);
            }
        });

        txfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUsernameActionPerformed(evt);
            }
        });

        lblUser.setText("Username");

        lblPass.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPass)
                        .addGap(90, 344, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnChangeAccount))
                            .addComponent(txfUsername, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLogIn)
                                    .addComponent(lblUser))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUser)
                .addGap(18, 18, 18)
                .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnLogIn)
                .addGap(18, 18, 18)
                .addComponent(btnChangeAccount)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfUsernameActionPerformed

    private void btnChangeAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeAccountActionPerformed
        if (txfUsername.getText().length() > 6 && txfPassword.getPassword().length > 6) {
            long usr = txfUsername.getText().hashCode() * SALT;
            long pass = Arrays.hashCode(txfPassword.getPassword()) * SALT;
            if (!Data.containsKey(usr)) {
                long confPass = Arrays.hashCode(JOptionPane.showInputDialog("Please confirm your password").toCharArray()) * SALT;
                if (confPass == pass) {
                    Data.put(usr, pass);
                    JOptionPane.showMessageDialog(null, "Success");
                } else {
                    JOptionPane.showMessageDialog(null, "Passwords do not match");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Username is already in use");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter a username and password longer than 6 digits");
        }

    }//GEN-LAST:event_btnChangeAccountActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
     
        long user = txfUsername.getText().hashCode() * SALT;
        long pass = Arrays.hashCode(txfPassword.getPassword()) * SALT;
        if (((Data.get(user))) == (pass)) {
            JOptionPane.showMessageDialog(null, "Welcome " + txfUsername.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Error - Incorrect username or password");
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DailyProgrammingPasswordProtection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DailyProgrammingPasswordProtection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DailyProgrammingPasswordProtection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DailyProgrammingPasswordProtection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DailyProgrammingPasswordProtection().setVisible(true);
            }
        });
    }

    public static boolean saveHashes() {
        try {
            FileOutputStream fos = new FileOutputStream("save.tmp");
            ObjectOutputStream oos = new ObjectOutputStream(fos);

            oos.writeObject(Data);
            oos.close();
            fos.close();
            return true;

        } catch (FileNotFoundException ex) {
            Logger.getLogger(DailyProgrammingPasswordProtection.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DailyProgrammingPasswordProtection.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    public static void readAllHashes() {
        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream("save.tmp"));

            Data = (HashMap<Long, Long>) ois.readObject();

            ois.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(DailyProgrammingPasswordProtection.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(DailyProgrammingPasswordProtection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeAccount;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txfPassword;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
